Repository Digital-Land-Platform/Digital-Land-Server, pull requests merged in 2024-12, with the labels that each got.

#84 fixing database seeders
  config/database.py
  main.py
  src/middleware/AuthManagment.py
  src/models/repository/AmenityRepository.py
  src/models/repository/LocationRepository.py
  src/models/repository/propertyRepository.py
  src/models/repository/userRepository.py
  src/seeders/amenity_seeder.py
  src/seeders/files/amenities.json
  src/seeders/files/locations.json
  src/seeders/location_seeder.py
  src/seeders/property_seeder.py
  src/seeders/seed_database.py
  src/seeders/user_seeder.py
Labels: Backend, fix

#88 Seeding production database
  file.log
  main.py
  src/seeders/seed_database.py
Labels: Backend, Highest Priority, Needs Reviews

#90 type mismatch
  src/graphql/property/types.py
Labels: bug, fix, Ready for Reviews, Needs Reviews

#86 Adjustments to handle auth0 authentication
  .github/workflows/main.yml
  src/RestAPI/Auth/login.py
  src/RestAPI/Auth/token.py
  src/graphql/property/query.py
Labels: Backend, Needs Reviews

#91 updating a payment method to create a transaction
  file.log
  src/graphql/payment/mutation.py
  src/graphql/payment/service.py
  src/graphql/payment/types.py
  src/graphql/transaction/services.py
  src/graphql/transaction/types.py
  src/graphql/users/query.py
  src/middleware/AuthManagment.py
  src/models/Payment.py
Labels: enhancement, Backend, Ready for Reviews, Needs Reviews

#93 Adding payment methods
  src/graphql/payment/mutation.py
  src/graphql/payment/query.py
  src/graphql/payment/types.py
  src/models/enums/PaymentMethod.py
Labels: Backend, fix, Highest Priority, Needs Reviews
